### ISSUE TITLE
Fix add new post

### ISSUE THREAD

**Issue by gresalahi** [tamiat/tamiat#92] opened 2018-01-24 21:27 UTC
Right now if I run the app from master branch and I try to create a new post it throws me this error:
 
```
[Vue warn]: Error in render: "TypeError: Cannot convert undefined or null to object"

found in

---> <Posts> at src\components\Admin\content\Posts.vue
       <Admin> at src\components\Admin.vue
         <App> at src\App.vue
           <Root>
```

**Comment by Abdelaziz18003** [comment] 2018-01-26 19:21
Hi @gresalahi, @mahnouman assinged me to work on this issue

**Comment by gresalahi** [comment] 2018-01-29 21:35
@michu1234  please test the implementation Abdelaziz provided in this issue. The implementation can be found on: https://github.com/Abdelaziz18003/tamiat/commit/506ac4cff34b889671da36bb90bdf435ec6c08b8

**Comment by michu1234** [comment] 2018-01-30 19:20
#### Creating post (on **master branch**) is impossible. The editor inside posts tab doesn't work. It looks like this

![editor test](https://user-images.githubusercontent.com/24733645/35586241-a1e65466-05fa-11e8-892c-7d612075c15f.png)

**Comment by michu1234** [comment] 2018-01-30 19:39
The problem is probably related to new version of  "vue-quill-editor": "^3.0.5"
With this version "vue-quill-editor": "^2.3.2" everything was fine

**Comment by gresalahi** [comment] 2018-01-31 20:41
@Abdelaziz18003 Please check the issue with the editor, provided above.

**Comment by Abdelaziz18003** [comment] 2018-01-31 22:07
@gresalahi @michu1234 I check it and it is Ok on my side I can't see any problem with the editor .. I tested with firefox 58 and chrome 63 .. I am using the recent version on the master branch .. I can't reproduce the issue

**Comment by Abdelaziz18003** [comment] 2018-01-31 22:37
@michu1234 was right .. the issue is related to the vue-quill-editor version .. my vue-quill-version was outdated when I tested it 30 mn ago. I updated it and I faces the same issue.
I checked the vue-quill-editor documentation and I found that the new version needs explicit imports of CSS files. anyway the issue is fixed. I will make a pull request for it.

**Comment by Abdelaziz18003** [comment] 2018-02-03 10:24
@gresalahi @mahnouman maybe this issue and #94  should be closed now .. due to merging the previous pull request

**Comment by mahnouman** [comment] 2018-02-07 20:06
Ok, thanks Abdelaziz, just saw your comment now. Closing.

**Closed by mahnouman** 2018-02-07 20:06 UTC
Labels: bug
