### ISSUE TITLE
Fix Unable to authorize access to project

### ISSUE THREAD

**Issue by gresalahi** [tamiat/tamiat#50] opened 2017-10-12 20:13 UTC
There is an issue after you run `firebase deploy` on step 7, it will get stuck showing the following error: 
`Error: Unable to authorize access to project tamiat-demo`.

This can be resolved by simply removing the `.firebaserc` and running the `firebase init` again and then selecting the project you have already created in firebase.

**Comment by coderpradp** [comment] 2018-10-31 16:27
The issue is with user not selecting the correct firebase instance during `firebase init`
Or the issue may have occurred due to commit of .firebaserc which is nolonger committed to the git
So it feels safe to close it.

**Closed by coderpradp** 2018-10-31 16:27 UTC
